# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msg_pkg/first_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class first_msg(genpy.Message):
  _md5sum = "4d5888a5a4bca89c6d6a476ac8a88a1a"
  _type = "custom_msg_pkg/first_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time start_time
uint16 msg_seq
uint16 original_num
"""
  __slots__ = ['start_time','msg_seq','original_num']
  _slot_types = ['time','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       start_time,msg_seq,original_num

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(first_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.start_time is None:
        self.start_time = genpy.Time()
      if self.msg_seq is None:
        self.msg_seq = 0
      if self.original_num is None:
        self.original_num = 0
    else:
      self.start_time = genpy.Time()
      self.msg_seq = 0
      self.original_num = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I2H().pack(_x.start_time.secs, _x.start_time.nsecs, _x.msg_seq, _x.original_num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_time is None:
        self.start_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.start_time.secs, _x.start_time.nsecs, _x.msg_seq, _x.original_num,) = _get_struct_2I2H().unpack(str[start:end])
      self.start_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I2H().pack(_x.start_time.secs, _x.start_time.nsecs, _x.msg_seq, _x.original_num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_time is None:
        self.start_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.start_time.secs, _x.start_time.nsecs, _x.msg_seq, _x.original_num,) = _get_struct_2I2H().unpack(str[start:end])
      self.start_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I2H = None
def _get_struct_2I2H():
    global _struct_2I2H
    if _struct_2I2H is None:
        _struct_2I2H = struct.Struct("<2I2H")
    return _struct_2I2H
