// Generated by gencpp from file manager/manager.msg
// DO NOT EDIT!


#ifndef MANAGER_MESSAGE_MANAGER_H
#define MANAGER_MESSAGE_MANAGER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manager
{
template <class ContainerAllocator>
struct manager_
{
  typedef manager_<ContainerAllocator> Type;

  manager_()
    : enabled(false)
    , speed(0.0)  {
    }
  manager_(const ContainerAllocator& _alloc)
    : enabled(false)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _enabled_type;
  _enabled_type enabled;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::manager::manager_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manager::manager_<ContainerAllocator> const> ConstPtr;

}; // struct manager_

typedef ::manager::manager_<std::allocator<void> > manager;

typedef boost::shared_ptr< ::manager::manager > managerPtr;
typedef boost::shared_ptr< ::manager::manager const> managerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manager::manager_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manager::manager_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manager::manager_<ContainerAllocator1> & lhs, const ::manager::manager_<ContainerAllocator2> & rhs)
{
  return lhs.enabled == rhs.enabled &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manager::manager_<ContainerAllocator1> & lhs, const ::manager::manager_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manager::manager_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manager::manager_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manager::manager_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manager::manager_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manager::manager_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manager::manager_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manager::manager_<ContainerAllocator> >
{
  static const char* value()
  {
    return "959738decaba41841790fb595d10b1d5";
  }

  static const char* value(const ::manager::manager_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x959738decaba4184ULL;
  static const uint64_t static_value2 = 0x1790fb595d10b1d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::manager::manager_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manager/manager";
  }

  static const char* value(const ::manager::manager_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manager::manager_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool enabled\n"
"float32 speed\n"
;
  }

  static const char* value(const ::manager::manager_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manager::manager_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enabled);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct manager_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manager::manager_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manager::manager_<ContainerAllocator>& v)
  {
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANAGER_MESSAGE_MANAGER_H
