// Generated by gencpp from file manager/SteeringControl.msg
// DO NOT EDIT!


#ifndef MANAGER_MESSAGE_STEERINGCONTROL_H
#define MANAGER_MESSAGE_STEERINGCONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manager
{
template <class ContainerAllocator>
struct SteeringControl_
{
  typedef SteeringControl_<ContainerAllocator> Type;

  SteeringControl_()
    : enabled(false)
    , steering_angle(0.0)  {
    }
  SteeringControl_(const ContainerAllocator& _alloc)
    : enabled(false)
    , steering_angle(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _enabled_type;
  _enabled_type enabled;

   typedef float _steering_angle_type;
  _steering_angle_type steering_angle;





  typedef boost::shared_ptr< ::manager::SteeringControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manager::SteeringControl_<ContainerAllocator> const> ConstPtr;

}; // struct SteeringControl_

typedef ::manager::SteeringControl_<std::allocator<void> > SteeringControl;

typedef boost::shared_ptr< ::manager::SteeringControl > SteeringControlPtr;
typedef boost::shared_ptr< ::manager::SteeringControl const> SteeringControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manager::SteeringControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manager::SteeringControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manager::SteeringControl_<ContainerAllocator1> & lhs, const ::manager::SteeringControl_<ContainerAllocator2> & rhs)
{
  return lhs.enabled == rhs.enabled &&
    lhs.steering_angle == rhs.steering_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manager::SteeringControl_<ContainerAllocator1> & lhs, const ::manager::SteeringControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manager::SteeringControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manager::SteeringControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manager::SteeringControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manager::SteeringControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manager::SteeringControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manager::SteeringControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manager::SteeringControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4bc179aa9c01f2acacbf2c87950c45d";
  }

  static const char* value(const ::manager::SteeringControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4bc179aa9c01f2aULL;
  static const uint64_t static_value2 = 0xcacbf2c87950c45dULL;
};

template<class ContainerAllocator>
struct DataType< ::manager::SteeringControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manager/SteeringControl";
  }

  static const char* value(const ::manager::SteeringControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manager::SteeringControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool enabled\n"
"float32 steering_angle\n"
;
  }

  static const char* value(const ::manager::SteeringControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manager::SteeringControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enabled);
      stream.next(m.steering_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SteeringControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manager::SteeringControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manager::SteeringControl_<ContainerAllocator>& v)
  {
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
    s << indent << "steering_angle: ";
    Printer<float>::stream(s, indent + "  ", v.steering_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANAGER_MESSAGE_STEERINGCONTROL_H
